#!/usr/bin/env python3
# ===========================================================
# ACCELERATION TABLE GENERATOR
# ===========================================================
# Generates acceleration.h — a lookup table of step *periods*
# (microseconds between steps) indexed by "accel step".
#
# How it's used by the firmware:
#   - current_accel_step ramps up while far from target, ramps
#     down as delta_steps shrinks (so it decelerates into the
#     target). It is clamped to [0, MAX_ACCEL_STEP].
#   - The period for the current accel step sets how long to
#     wait before taking the next motor step. Small period =
#     fast; large period = slow.
#   - Because target_accel_step is capped by delta_steps, the
#     motor automatically slows as it nears the target — one
#     table drives both accel and decel (trapezoidal motion).
#
# Approach adapted from scottbez1/splitflap (Apache-2.0),
# retuned for the 28BYJ-48 in half-step mode at 5V.
#
# Run:  python3 generate_acceleration.py
# ===========================================================

import os

# --- TUNABLES (28BYJ-48, half-step, 5V) ---
# MIN_PERIOD_MICROS  = fastest sustained step rate (top speed).
#                      1600us => ~625 steps/s. Lower = faster but
#                      risks stalling/skipping. Tune with test 02.
# MAX_PERIOD_MICROS  = slowest step rate (the very first step off
#                      standstill). Big value = gentle start.
# ACCEL_TIME_MICROS  = time spent ramping from slow to top speed.
# IDLE_PERIOD_MICROS = period stored at accel step 0 (motor idle).
MIN_PERIOD_MICROS = 1600
MAX_PERIOD_MICROS = 10000
ACCEL_TIME_MICROS = 200000
IDLE_PERIOD_MICROS = 1600

_TEMPLATE = """// ===========================================================
// ACCELERATION TABLE  (AUTOGENERATED — DO NOT EDIT BY HAND)
// ===========================================================
// Regenerate with: python3 generate_acceleration.py
//
// ACCEL_STEP_PERIODS[i] = microseconds to wait before the next
// motor step when current_accel_step == i.
//   index 0            -> motor idle
//   index 1            -> slowest moving step (just started)
//   index MAX_ACCEL_STEP -> fastest (top speed)
// ===========================================================

#ifndef ACCELERATION_H
#define ACCELERATION_H

#include <stdint.h>

namespace Acceleration {{
    const uint16_t ACCEL_STEP_PERIODS[] = {{{periods_array}}};
    const uint8_t  MAX_ACCEL_STEP = {max_accel_step};
}}

#endif
"""


def run(output_file_path):
    min_velocity = 1000000.0 / MAX_PERIOD_MICROS   # steps/sec at slowest
    max_velocity = 1000000.0 / MIN_PERIOD_MICROS   # steps/sec at fastest

    t = 0
    ramp_periods = [IDLE_PERIOD_MICROS]
    while t < ACCEL_TIME_MICROS:
        velocity = min_velocity + (max_velocity - min_velocity) * (float(t) / ACCEL_TIME_MICROS)
        if velocity > max_velocity:
            velocity = max_velocity
        period = int(1000000 / velocity)
        ramp_periods.append(period)
        t += period

    assert len(ramp_periods) <= 255, "ramp step count would exceed a uint8_t index"

    with open(output_file_path, "w") as f:
        f.write(_TEMPLATE.format(
            periods_array=", ".join(str(p) for p in ramp_periods),
            max_accel_step=len(ramp_periods) - 1,
        ))
    print("Wrote {} ({} accel steps)".format(output_file_path, len(ramp_periods) - 1))


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "acceleration.h")
    run(out)
